/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppStockCountRouteImport } from './routes/app.stock-count'
import { Route as AppSalesRouteImport } from './routes/app.sales'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppOcrRouteImport } from './routes/app.ocr'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppBulkImportRouteImport } from './routes/app.bulk-import'
import { Route as AppAdvisorRouteImport } from './routes/app.advisor'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AppAdvisorHistoryRouteImport } from './routes/app.advisor.history'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppStockCountRoute = AppStockCountRouteImport.update({
  id: '/stock-count',
  path: '/stock-count',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOcrRoute = AppOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBulkImportRoute = AppBulkImportRouteImport.update({
  id: '/bulk-import',
  path: '/bulk-import',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisorRoute = AppAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAdvisorHistoryRoute = AppAdvisorHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppAdvisorRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/advisor': typeof AppAdvisorRouteWithChildren
  '/app/bulk-import': typeof AppBulkImportRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/ocr': typeof AppOcrRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/stock-count': typeof AppStockCountRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/advisor/history': typeof AppAdvisorHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/advisor': typeof AppAdvisorRouteWithChildren
  '/app/bulk-import': typeof AppBulkImportRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/ocr': typeof AppOcrRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/stock-count': typeof AppStockCountRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/advisor/history': typeof AppAdvisorHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/advisor': typeof AppAdvisorRouteWithChildren
  '/app/bulk-import': typeof AppBulkImportRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/ocr': typeof AppOcrRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/stock-count': typeof AppStockCountRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/advisor/history': typeof AppAdvisorHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/advisor'
    | '/app/bulk-import'
    | '/app/dashboard'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/ocr'
    | '/app/reports'
    | '/app/sales'
    | '/app/stock-count'
    | '/app/users'
    | '/app/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/advisor/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/advisor'
    | '/app/bulk-import'
    | '/app/dashboard'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/ocr'
    | '/app/reports'
    | '/app/sales'
    | '/app/stock-count'
    | '/app/users'
    | '/app'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/advisor/history'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/advisor'
    | '/app/bulk-import'
    | '/app/dashboard'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/ocr'
    | '/app/reports'
    | '/app/sales'
    | '/app/stock-count'
    | '/app/users'
    | '/app/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/advisor/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stock-count': {
      id: '/app/stock-count'
      path: '/stock-count'
      fullPath: '/app/stock-count'
      preLoaderRoute: typeof AppStockCountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales': {
      id: '/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ocr': {
      id: '/app/ocr'
      path: '/ocr'
      fullPath: '/app/ocr'
      preLoaderRoute: typeof AppOcrRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bulk-import': {
      id: '/app/bulk-import'
      path: '/bulk-import'
      fullPath: '/app/bulk-import'
      preLoaderRoute: typeof AppBulkImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advisor': {
      id: '/app/advisor'
      path: '/advisor'
      fullPath: '/app/advisor'
      preLoaderRoute: typeof AppAdvisorRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/advisor/history': {
      id: '/app/advisor/history'
      path: '/history'
      fullPath: '/app/advisor/history'
      preLoaderRoute: typeof AppAdvisorHistoryRouteImport
      parentRoute: typeof AppAdvisorRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdvisorRouteChildren {
  AppAdvisorHistoryRoute: typeof AppAdvisorHistoryRoute
}

const AppAdvisorRouteChildren: AppAdvisorRouteChildren = {
  AppAdvisorHistoryRoute: AppAdvisorHistoryRoute,
}

const AppAdvisorRouteWithChildren = AppAdvisorRoute._addFileChildren(
  AppAdvisorRouteChildren,
)

interface AppRouteChildren {
  AppAdvisorRoute: typeof AppAdvisorRouteWithChildren
  AppBulkImportRoute: typeof AppBulkImportRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppOcrRoute: typeof AppOcrRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppStockCountRoute: typeof AppStockCountRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvisorRoute: AppAdvisorRouteWithChildren,
  AppBulkImportRoute: AppBulkImportRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppOcrRoute: AppOcrRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppStockCountRoute: AppStockCountRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
